data<-read.table("./household_power_consumption.txt",head=TRUE,sep=";")
data$Date<-as.Date(data$Date,format="%d/%m/%Y")
dataSub<-subset(data,Date =="2007-02-01" | Date == "2007-02-02")
dataSub$Global_active_power<-as.numeric(as.character(dataSub$Global_active_power))
png(file="plot1.png",height=480,width=480)
hist(dataSub$Global_active_power,xlab="Global Active Power (kilowatts)",main="Global Active Power",col="red")
dev.off()